### ISSUE TITLE
Error in snipMate#GetSnippetsForWordBelowCursor()

### ISSUE THREAD

**Issue by zhester** [garbas/vim-snipmate#187]
I was getting an error about an invalid list index (0) from this function (line 5).  There was a recent change to add a check, but the operator precedence places && ahead of >.  So, the short-circuit && doesn't prevent attempting to index the parts list with 0.  Explicitly grouping the comparisons fixes the problem for me.

I changed line 5 of the function from this:

if len(parts) > 1 && len(parts[0]) > 1

to this:

if (len(parts) > 1) && (len(parts[0]) > 1)

Everything works great now.

**Comment by ajzafar** [comment]
Looking at `:h expression-syntax`, the logical AND `&&` is in fact less significant than the comparison `>`, as in every programming language. As such I'd like to actually understand what problem you're experiencing rather than accept on faith that what should in theory change nothing is actually fixing the problem. Can you start by sharing your Vim version (including the patch number) and the actual error Vim gives you?

**Comment by zhester** [comment]
I may have posted this in error.  My apologies.  It was a frustrating error that kept happening each time I hit the tab key.  The error was:

Error detected while processing function snipMate#TriggerSnippet..snipMate#GetSnippetsForWordBelowCursor:
line    5:
E684: list index out of range: 0

Not that it matters now, but I'm running version 7.4, patches 1-527.

I thought I updated snipMate, but kept seeing the error.  However, after removing and re-installing the plugin, everything is working fine.  I'll have to admit that I don't understand Vim well enough to track down the real source of these errors.  I will close the ticket.

Again, my sincerest apologies.

Thank you for working on a great plugin that I consider pretty important for my productivity.
