### ISSUE TITLE
SnipMate:Expression: Vim(let):E117: Unknown function: uvm_component_utils

### ISSUE THREAD

**Issue by morshalev** [garbas/vim-snipmate#215]
when i try use this snip

snippet class uvm_object ..
	class ${1:} extends uvm_object;
	    `uvm_object_utils($1)
			//Variable Declaration
	
	    //Class Constructor
	    function new(string name = "$1");
	        super.new(name);
	    endfunction : new

	    //Rest of code here

	endclass : $1 

I got this error:
SnipMate:Expression: Vim(let):E117: Unknown function: uvm_component_utils
why?

**Comment by ajzafar** [comment]
There is a backtick \` in your snippet that is causing SnipMate to try expression evaluation `:h SnipMate-eval`. If you need backtick in the snippet output, escape it with a backslash \\\`. (This requires version 1 of the snippet parser. I don't think there's a solution using the legacy parser.) Otherwise just remove it.
