### ISSUE TITLE
Cannot insert snippets recursively

### ISSUE THREAD

**Issue by morrizon** [garbas/vim-snipmate#223]
When I write:
```vim
int<Tab>MyInterface<Tab>met<Tab>MyMethod<Tab>
```
I expect:
```php
interface MyInterface {
    public function MyMethod()
    {
        _
    }
}
```
But I get:
```php
interface MyInterface {
    met
}MyMethod<Tab>_
```

Snippet file:
```vim
snippet met
    public function ${1}()
    {
        ${2}
    }
snippet int
    interface ${1} {
        ${2}
    }
```

**Comment by ajzafar** [comment]
What you're expecting isn't happening because you're still in the snippet when you want to be leaving it. SnipMate adds a special zeroth tabstop to the end of every snippet if one isn't included representing the final end of the snippet, so when you hit `<Tab>` you're jumping to to the final tabstop instead of expanding a snippet. The solution is to either make use of the zeroth tabstop, probably by changing the `${2}` in each snippet to `${0}`, or you can make use of the `<Plug>snipMateTrigger` mapping, which will try to expand a snippet regardless of whether you're already in one. The relevant helptags are `:h SnipMate-zero-tabstop` and `:h SnipMate-mappings`.
