### ISSUE TITLE
Zero shiftwidth is not supported

### ISSUE THREAD

**Issue by rglassett** [garbas/vim-snipmate#227]
Since 7.3.629, Vim allows `shiftwidth` to follow `tabstop` when `shiftwidth=0`. Using this option breaks indentation when snippets are expanded.

I spiked out a fix but haven't bothered to learn vspec and make a PR. Feel free to use this code if it makes sense.

To autoload/snipmate/util.vim, I added:

```viml
function! snipmate#util#tabwidth()
    if &sts > 0
      return &sts
    else
      return exists('*shiftwidth') ? shiftwidth() : &sw
    endif
endfunction
```

I changed the following line from autoload/snipmate/legacy.vim:

```viml
" old
return substitute(snippet, '\t', repeat(' ', (&sts > 0) ? &sts : &sw), 'g')

" new
return substitute(snippet, '\t', repeat(' ', snipmate#util#tabwidth()), 'g')
```

And the `s:indent` function in autoload/snipmate/parse.vim to read:

```viml
function! s:indent(count) abort
    if &expandtab
        let shift = repeat(' ', snipmate#util#tabwidth())
    else
        let shift = "\t"
    endif
    return repeat(shift, a:count)
endfunction
```

**Comment by ajzafar** [comment]
Thanks for the contribution! Pull requests are really easy though, and you should learn. I'm going to be honest, I was less enthused about this because it wasn't in the form of a pull request. It's a key GitHub feature. Even if you're not using GitHub, it's worth at least knowing how to use git to generate a patch.

Thanks again!
