### ISSUE TITLE
How to specify multiple snippets for the same trigger?

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [garbas/vim-snipmate#242]
I've already tried:

    snippet mytrigger
        completion1
        completion2

and

    snippet mytrigger
        completion1
    snippet mytrigger
        completion2

The first one makes it paste both completions, the second one makes it overwrite the completion1, only having completion2.

I'd like to see a list of available completions for one and the same trigger.

Is this possible? If so, how?

**Comment by ajzafar** [comment]
@ZelphirKaltstahl This is very possible! A description for each snippet sharing a trigger is need however, otherwise SnipMate will think you wanted the second to override the first. All information about this can be found at `:h SnipMate-multisnip`. Let us know if you have more questions after reading that.

**Comment by ZelphirKaltstahl** [comment]
Thanks! That will come in handy! This solved the issue.
