### ISSUE TITLE
VISUAL strange behaviour and extra line

### ISSUE THREAD

**Issue by 0x62ash** [garbas/vim-snipmate#245]
I have MacVim 8.0.329 (127) on macOS 10.12.3 and vim-snipmates commit 2d70860ba49afc83cb5902acb99174e3cf08538d (Mon Nov 14 16:13:00 2016 -0500)

First, i want to say that snippet like this (from [vim-snippets](https://github.com/honza/vim-snippets/blob/master/snippets/c.snippets#L54-L57)) doesn't work correctly from the box
```
snippet if
    if (${1:true}) {
        ${0:${VISUAL}}
    }
```

Example
```
1
2
3
```
Substitues to 
```
if (true) {
    truetrue
    2
    3}true
    2
    3
}
```

Solution for this is to set parser version via .vimrc:
```
let g:snipMate = {}
let g:snipMate.snippet_version = 1
```

But even with this settings you will get one empty extra line:
```
if (true) {
    1
    2
    3
    
}
```

Is there any way to exclude this extra line?

**Comment by ddaza** [comment]
I am seeing the same behavior. 
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 18 2017 22:56:36)
Included patches: 1-313, 315-339

**Comment by ajzafar** [comment]
Alright for version 0, there are a few problems. One is that in version 0, the correct visual placeholder is `{VISUAL}`, without the `$`. The others are a result of limitations of the legacy parser, limitations that I wrote the version 1 parser to get away from. Simply put I'm not going to fix those problems.

With version 1, the extra empty line is a result of using visual line mode instead of just visual mode. When using plain ol' visual mode, there is no extra line. Consider a snippet with text before and after a visual placeholder, such as

    snippet foo
        foo $VISUAL bar

I think it's reasonable that someone might want to use visual character mode to keep all three pieces of text on one line sometimes, but other times want to use visual line mode to put a bunch of lines between the "foo" and "bar". For this reason I'm not inclined to change anything at this point. Unless you can persuade me otherwise.

Having said that, I will leave this open in case at some point in the future someone comes up with a reasonable way to specify that some placeholders are to be characterwise and others linewise (or even blockwise).

**Comment by 0x62ash** [comment]
Thank you for response.

Maybe it's possible to check that if $VISUAL placed at line end then do not put extra new line?

**Comment by ajzafar** [comment]
That sounds reasonable to me. Fixed in the above commits. Thanks!
