### ISSUE TITLE
Can I change the "snippet_dirs" to a seperate Dropbox folder?

### ISSUE THREAD

**Issue by llinfeng** [garbas/vim-snipmate#249]
## Feature request

I use snippets on a hourly basis, and more often than not, I will make changes to the snippets. However, currently, all snippets seems to be canned within the `Vim-snipmate` plugin. Thus, it makes it very hard to me to keep the snippets up-to-date when I switch workstations (e.g., from a Windows desktop machine to a laptop).

It would nice to give users an option to **source** a specific folder outside the installation package of the plugin.

## Failed attempts
1. Tried to change the following setting, in vain:
```    vim
let g:SnipMate['snippet_dirs']
                \ = funcref#Function('return split(&runtimepath,",")')
```
2. Tried to add the following to my `_vimrc` (on a Windows machine):
``` vim
    set rtp+=c:\Users\llinfeng\Dropbox\snippet\
```

3. Have also tried the solution in issue https://github.com/garbas/vim-snipmate/issues/12, as follows. Yet, nothing happens after I pressing the `<tab>` key for completion. 

```vim
let g:snipMate = {}
let g:snipMate['snippet_dirs'] = funcref#Function('return ["~/.vim/snippets"]')
```

## Ideal solution

Please advise the specific settings I can use to have all my *snippets* stored in one Dropbox folder, for example, under `~Dropbox\Tool_Private\Vim_Settings\Snippets\`

``` vim
" setting pending
```

**Comment by ajzafar** [comment]
There are currently two ways to do this, both of which you were close to doing:

1. Add a directory to `'rtp'`. Note that with this approach, SnipMate will look in the given directory for a directory named `snippets`, and it'll look in *that* directory for snippets. Using the directory in your post, you could either put your snippets in `c:\Users\llinfeng\Dropbox\snippet\snippets` or rename your directory to `snippets`. Then you would do either `set rtp+=c:\Users\llinfeng\Dropbox\snippet` or `set rtp+=c:\Users\llinfeng\Dropbox`, respectively. I recommend this approach.

2. Alternatively you can add the following to your vimrc. I don't recommend this approach.

    let g:snipMate = {}        " This line is only necessary if the g:snipMate variable has not already been created
    let g:snipMate['snippet_dirs'] = [ 'c:\Users\llinfeng\Dropbox\snippet']

I recommend the first option because there is a very good chance I will be removing the second option. It'll be part of a bigger change I've been thinking about for a long time. Plus it follows Vim's approach to this sort of thing, which I'm more inclined to follow given Vim 8's approach to package management.

**Comment by llinfeng** [comment]
@ajzafar  Thanks a lot!

### note
The directory name, `snippets`, is case-sensitive. All `*.snippets` shall go **under** this folder/directory.

### The settings that worked:
* In `_vimrc`, specify: `set rtp+=c:\Users\llinfeng\Dropbox\Tool_Private\Vim_Settings\`
* Make sure snippets (files ending with `.snippets` extension) are stored as follows:
![snippet_locals](https://cloud.githubusercontent.com/assets/5890407/24580825/6924d9d4-16dd-11e7-97fd-939024cb9227.png)

**Comment by vrkansagara** [comment]
The latest solution is here https://github.com/honza/vim-snipmate/commit/581a4d1c0696bc79f461275957d5ade79624c4b8#commitcomment-48874436

**Comment by llinfeng** [comment]
@vrkansagara How is [what you wrote](https://github.com/honza/vim-snipmate/commit/581a4d1c0696bc79f461275957d5ade79624c4b8#commitcomment-48874436) different from what @ajzafar provided as the solution to my original post? I suppose there are now two ways to source snippets elsewhere, as below
```
; This is the old recommended setting form 2017, which worked fine over 4+ years for me.
; Note, the `filetype.snippets` files should be nested under the full path specified below.
set rtp+="/full/path/to/folder/of/snippets/"
; This is another way to specify the same thing. A single period in Vim concatinates two strings.
; This was referred to as "the lastest solution".
let &runtimepath.=','.'/full/path/to/folder/of/snippets/' 
```
Since these two entries in `.vimrc` should be identical in practice, I am listing them here together.
