### ISSUE TITLE
.snippets file accept only TAB for identation

### ISSUE THREAD

**Issue by rodhash** [garbas/vim-snipmate#290]
Hello,

Just migrated from vim-snip and found one identation issue. Lemonade helped fix in another repo and it seems the same issue is found here too.. I searched for similar issues but found none, so I'm raising this one

The issue basically is: we can't use space for identation, as soon as I SPACE idented the highlight error was triggered:
![Screenshot from 2022-09-09 02-13-14](https://user-images.githubusercontent.com/29671981/189277291-92dcebfc-2309-44ee-ace0-987830ac16dc.png)

This seems to be a quick and simple solution, updated the syntax file.

So if you're interested in that, just raised the PR #289 allowing the use of SPACE char as well:

Now we can use both, TAB indented or SPACES indented:
![Screenshot from 2022-09-09 02-13-54](https://user-images.githubusercontent.com/29671981/189277445-f63cb429-64ce-444a-a925-a9d1e2f9ec4b.png)

Cheers

**Comment by ajzafar** [comment]
As I said in the pull request, it's not actually a simple fix as adjusting syntax files does not affect how SnipMate actually operates. Spaces will still be wrong.

While I've had an idea on how to make this more flexible, so that spaces would be allowable, it's nowhere near implementation. Currently I think it makes a lot of sense to stick with the current requirement of hard tabs. The `'listchars'` option may help you see where those are or are not.

**Comment by rodhash** [comment]
I didn't understand what the issue is, but alright.. I'll keep the fix in my local branch while the Space identation isn't allowed here... curious thing is, space identation work fine here, even with the syntax files highlighting them as error

**Comment by rodhash** [comment]
Anyway thx for the details.. will keep an eye on upstream ..  I'm still experimenting with other snippets tools and will check back later

**Comment by ajzafar** [comment]
@rodhash I am not sure what you're experiencing on your end, but spaces in `.snippets` files do not work to denote the contents of a snippet. Here's what happens when I try on my end:
[![asciicast](https://asciinema.org/a/NYbVXY5ekRYBAEGpo08E8Dz5B.svg)](https://asciinema.org/a/NYbVXY5ekRYBAEGpo08E8Dz5B)
